name: Mac OS

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/build_and_test.yml'
      - '.github/workflows/wsl.yml'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/build_and_test.yml'
      - '.github/workflows/wsl.yml'
  workflow_dispatch:
    paths-ignore:
      - 'doc/**'
      - '.github/workflows/codeql.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/build_and_test.yml'
      - '.github/workflows/wsl.yml'

jobs:
  build:
    strategy:
      matrix:
        pg: [15, 18]
    name: macOS â€” PostgreSQL ${{ matrix.pg }}
    runs-on: macos-latest
    steps:
      - run: brew update
      - run: brew install postgresql@${{ matrix.pg }} libpq@${{ matrix.pg }}
      - run: brew install boost
      - run: brew services start postgresql@${{ matrix.pg }}
      - uses: actions/checkout@v6
      - run: make && make tdkc && make install
      - run: pg_isready -t 60 || (cat /usr/local/var/log/potgres*.log; false)
      - run: echo "POSTGRESQL_CONFIG=$(psql -t -c 'SHOW config_file' postgres)" >> $GITHUB_ENV
      - run: echo "shared_preload_libraries = 'provsql'" >> $POSTGRESQL_CONFIG
      - run: brew services restart postgresql@${{ matrix.pg }}
      - run: "perl -i -pe 's/ c2d//; s/ d4//; s/ weightmc//; s/ dsharp//; s/ view_circuit_multiple//; s/test: *$//' test/schedule"
      - run: pg_isready -t 60 || (cat /usr/local/var/log/potgres*.log; false)
      - run: make installcheck || bash -c "shopt -s nullglob; cat /tmp/tmp.provsql*/regression.diffs && for i in /tmp/provsql*; do echo $i && cat $i; done; false"
